package io.github.dominicschaff.bible

fun String.afrikaansBookName() = when (this) {
    "gn" -> "Genesis"
    "ex" -> "Eksodus"
    "lv" -> "Levitikus"
    "nm" -> "Numeri"
    "dt" -> "Deuteronomium"
    "js" -> "Josua"
    "jud" -> "Rigters"
    "rt" -> "Rut"
    "1sm" -> "1 Samuel"
    "2sm" -> "2 Samuel"
    "1kgs" -> "1 Konings"
    "2kgs" -> "2 Konings"
    "1ch" -> "1 Kronieke"
    "2ch" -> "2 Kronieke"
    "ezr" -> "Esra"
    "ne" -> "Nehemia"
    "et" -> "Ester"
    "job" -> "Job"
    "ps" -> "Psalms"
    "prv" -> "Spreuke van Salomo"
    "ec" -> "Prediker"
    "so" -> "Hooglied van Salomo"
    "is" -> "Jesaja"
    "jr" -> "Jeremia"
    "lm" -> "Klaagliedere van Jeremia"
    "ez" -> "Esegiël"
    "dn" -> "Daniël"
    "ho" -> "Hosea"
    "jl" -> "Joël"
    "am" -> "Amos"
    "ob" -> "Obadja"
    "jn" -> "Jona"
    "mi" -> "Miga"
    "na" -> "Nahum"
    "hk" -> "Habakuk"
    "zp" -> "Sefanja"
    "hg" -> "Haggai"
    "zc" -> "Sagaria"
    "ml" -> "Maleagi"
    "mt" -> "Matteus"
    "mk" -> "Markus"
    "lk" -> "Lukas"
    "jo" -> "Johannes"
    "act" -> "Die handelinge van die apostels"
    "rm" -> "Romeine"
    "1co" -> "1 Korintiërs"
    "2co" -> "2 Korintiërs"
    "gl" -> "Galasiërs"
    "eph" -> "Effesiërs"
    "ph" -> "Filippense"
    "cl" -> "Kolossense"
    "1ts" -> "1 Tessalonisense"
    "2ts" -> "2 Tessalonisense"
    "1tm" -> "1 Timoteus"
    "2tm" -> "2 Timoteus"
    "tt" -> "Titus"
    "phm" -> "Filemon"
    "hb" -> "Hebreërs"
    "jm" -> "Jakobus"
    "1pe" -> "1 Petrus"
    "2pe" -> "2 Petrus"
    "1jo" -> "1 Johannes"
    "2jo" -> "2 Johannes"
    "3jo" -> "3 Johannes"
    "jd" -> "Judas"
    "re" -> "Die Openbaring"
    else -> "---"
}